# Generated by Django 3.0.5 on 2021-02-22 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('story', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'campaign',
                'ordering': ('name',),
            },
        ),
    ]
