# Generated by Django 3.0.5 on 2021-02-28 17:36

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('armor_type', models.CharField(choices=[('LIGHT', 'Light Armor'), ('MEDIUM', 'Medium Armor'), ('HEAVY', 'Heavy Armor'), ('SHIELD', 'Shield')], max_length=10)),
                ('cost', models.PositiveSmallIntegerField()),
                ('armor_class', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)])),
                ('armor_class_increase', models.PositiveSmallIntegerField(default=0)),
                ('dex_modifier_max', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('strength_requirement', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)])),
                ('stealth_disadvantage', models.BooleanField()),
                ('weight', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'armor',
                'ordering': ('armor_type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('weapon_type', models.CharField(choices=[('SIMPLE_MELEE', 'Simple Melee Weapon'), ('SIMPLE_RANGED', 'Simple Ranged Weapon'), ('MARTIAL_MELEE', 'Martial Melee Weapon'), ('MARTIAL_RANGED', 'Martial Ranged Weapon')], max_length=15)),
                ('normal_range', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('maximum_range', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
            ],
            options={
                'db_table': 'weapon',
                'ordering': ('weapon_type', 'name'),
            },
        ),
    ]
