# Generated by Django 3.1.6 on 2021-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_money_mixin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.CharField(blank=True, choices=[('ARTISANS_TOOLS', "Artisan's Tools"), ('GAMING_SET', 'Gaming Set'), ('MUSICAL_INSTRUMENT', 'Musical Instrument'), (None, 'Other')], default=None, max_length=20, null=True),
        ),
    ]
