# Generated by Django 3.1.6 on 2021-04-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_blank_on_nullable_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdventuringGearPack',
            new_name='EquipmentPackGear',
        ),
        migrations.AlterModelTable(
            name='equipmentpackgear',
            table='equipment_pack_gear',
        ),
    ]
