# Generated by Django 3.1.6 on 2021-05-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_rename_equipment_pack_gear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventuringgear',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
