# Generated by Django 3.1.6 on 2021-05-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_quantity_default_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentpack',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
