# Generated by Django 3.1.6 on 2021-05-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_equipmentpack_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentpack',
            name='gear',
            field=models.ManyToManyField(related_name='equipment_pack', through='equipment.EquipmentPackGear', to='equipment.AdventuringGear'),
        ),
    ]
