# Generated by Django 3.1.6 on 2021-05-16 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_equipment_pack_gear_related_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='damage',
        ),
        migrations.AddField(
            model_name='weapon',
            name='damage_die',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='weapon',
            name='damage_die_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weapon',
            name='damage_type',
            field=models.CharField(choices=[('SLASHING', 'Slashing'), ('PIERCING', 'Piercing'), ('BLUDGEONING', 'Bludgeoning'), ('POISON', 'Poison'), ('ACID', 'Acid'), ('FIRE', 'Fire'), ('COLD', 'Cold'), ('RADIANT', 'Radiant'), ('NECROTIC', 'Necrotic'), ('LIGHTNING', 'Lightning'), ('THUNDER', 'Thunder'), ('FORCE', 'Force'), ('PSYCHIC', 'Psychic')], default='SLASHING', max_length=12),
        ),
    ]
