# Generated by Django 3.1.6 on 2021-05-16 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_standardise_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='ammunition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='finesse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='heavy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='light',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='loading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='reach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='thrown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='two_handed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='versatile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='maximum_range',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='normal_range',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
