# Generated by Django 3.1.6 on 2021-05-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_weapon_properties'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='characteradventuringgear',
            table='character_adventuring_gear',
        ),
    ]
