# Generated by Django 3.1.6 on 2021-05-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_remove_characteradventuringgear_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
