# Generated by Django 3.0.5 on 2021-02-22 19:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('hit_die', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(20)])),
                ('hit_die_count', models.PositiveSmallIntegerField(default=1)),
                ('strength', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30)])),
                ('dexterity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30)])),
                ('constitution', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30)])),
                ('intelligence', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30)])),
                ('wisdom', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30)])),
                ('charisma', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30)])),
            ],
            options={
                'db_table': 'monster_type',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('max_hp', models.PositiveSmallIntegerField()),
                ('current_hp', models.PositiveSmallIntegerField()),
                ('armor_class', models.PositiveSmallIntegerField()),
                ('strength', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('dexterity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('constitution', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('intelligence', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('wisdom', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('charisma', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('backstory', models.TextField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('monster_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monster.MonsterType')),
            ],
            options={
                'db_table': 'monster',
                'ordering': ('first_name', 'last_name', 'monster_type'),
            },
        ),
    ]
