# Generated by Django 3.0.5 on 2021-02-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='temporary_hp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
