# Generated by Django 3.1.6 on 2021-04-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0003_auto_20210323_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='backstory',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='campaign',
        ),
    ]
