# Generated by Django 3.1.6 on 2021-04-11 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0006_money_mixin'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstertype',
            name='armor_class',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
