# Generated by Django 3.1.6 on 2021-04-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0007_monstertype_armor_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='copper',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='electrum',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='gold',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='platinum',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='silver',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
