# Generated by Django 3.0.5 on 2021-02-22 19:12

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('hit_die', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'character_class',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CharacterRace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('speed', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('strength_increase', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)])),
                ('dexterity_increase', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)])),
                ('constitution_increase', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)])),
                ('intelligence_increase', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)])),
                ('wisdom_increase', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)])),
                ('charisma_increase', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)])),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None)),
            ],
            options={
                'db_table': 'character_race',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('max_hp', models.PositiveSmallIntegerField()),
                ('current_hp', models.PositiveSmallIntegerField()),
                ('armor_class', models.PositiveSmallIntegerField()),
                ('strength', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('dexterity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('constitution', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('intelligence', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('wisdom', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('charisma', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('backstory', models.TextField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.CharacterClass')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.CharacterRace')),
            ],
            options={
                'db_table': 'character',
                'ordering': ('first_name', 'last_name', 'race', 'level'),
            },
        ),
    ]
