# Generated by Django 3.0.5 on 2021-02-28 17:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='temporary_hp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='armor_proficiencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LIGHT', 'Light Armor'), ('MEDIUM', 'Medium Armor'), ('HEAVY', 'Heavy Armor'), ('SHIELD', 'Shield')], max_length=10), default=list, size=None),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='primary_abilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CHARISMA', 'Charisma'), ('CONSTITUTION', 'Constitution'), ('DEXTERITY', 'Dexterity'), ('INTELLIGENCE', 'Intelligence'), ('STRENGTH', 'Strength'), ('WISDOM', 'Wisdom')], max_length=15), default=list, size=None),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='saving_throw_proficiencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CHARISMA', 'Charisma'), ('CONSTITUTION', 'Constitution'), ('DEXTERITY', 'Dexterity'), ('INTELLIGENCE', 'Intelligence'), ('STRENGTH', 'Strength'), ('WISDOM', 'Wisdom')], max_length=15), default=list, size=None),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='weapon_proficiencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SIMPLE_MELEE', 'Simple Melee Weapon'), ('SIMPLE_RANGED', 'Simple Ranged Weapon'), ('MARTIAL_MELEE', 'Martial Melee Weapon'), ('MARTIAL_RANGED', 'Martial Ranged Weapon')], max_length=15), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='characterrace',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
