# Generated by Django 3.0.5 on 2021-02-28 17:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_proficiencies_and_temp_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='armor_proficiencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LIGHT', 'Light Armor'), ('MEDIUM', 'Medium Armor'), ('HEAVY', 'Heavy Armor'), ('SHIELD', 'Shield')], max_length=10), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='primary_abilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CHARISMA', 'Charisma'), ('CONSTITUTION', 'Constitution'), ('DEXTERITY', 'Dexterity'), ('INTELLIGENCE', 'Intelligence'), ('STRENGTH', 'Strength'), ('WISDOM', 'Wisdom')], max_length=15), size=None),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='saving_throw_proficiencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CHARISMA', 'Charisma'), ('CONSTITUTION', 'Constitution'), ('DEXTERITY', 'Dexterity'), ('INTELLIGENCE', 'Intelligence'), ('STRENGTH', 'Strength'), ('WISDOM', 'Wisdom')], max_length=15), size=None),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='weapon_proficiencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SIMPLE_MELEE', 'Simple Melee Weapon'), ('SIMPLE_RANGED', 'Simple Ranged Weapon'), ('MARTIAL_MELEE', 'Martial Melee Weapon'), ('MARTIAL_RANGED', 'Martial Ranged Weapon')], max_length=15), null=True, size=None),
        ),
    ]
