# Generated by Django 3.1.6 on 2021-03-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('character', '0003_auto_20210228_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='armor_proficiencies',
        ),
        migrations.AddField(
            model_name='characterclass',
            name='armor_proficiencies',
            field=models.ManyToManyField(null=True, to='equipment.Armor'),
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='weapon_proficiencies',
        ),
        migrations.AddField(
            model_name='characterclass',
            name='weapon_proficiencies',
            field=models.ManyToManyField(null=True, to='equipment.Weapon'),
        ),
    ]
