# Generated by Django 3.1.6 on 2021-04-01 19:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20210401_2120'),
        ('character', '0005_auto_20210401_2120'),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='adventuring_gear',
            field=models.ManyToManyField(blank=True, through='equipment.CharacterAdventuringGear', to='equipment.AdventuringGear'),
        ),
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.ManyToManyField(blank=True, through='equipment.CharacterArmor', to='equipment.Armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.ManyToManyField(blank=True, through='features.CharacterFeat', to='features.Feat'),
        ),
        migrations.AddField(
            model_name='character',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='character',
            name='tools',
            field=models.ManyToManyField(blank=True, to='equipment.Tool'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, through='equipment.CharacterWeapon', to='equipment.Weapon'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='features',
            field=models.ManyToManyField(blank=True, through='features.CharacterClassFeature', to='features.Feat'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='armor_proficiencies',
            field=models.ManyToManyField(blank=True, to='equipment.Armor'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='weapon_proficiencies',
            field=models.ManyToManyField(blank=True, to='equipment.Weapon'),
        ),
    ]
