# Generated by Django 3.1.6 on 2021-04-06 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('character', '0006_auto_20210401_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='backstory',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign'),
        ),
    ]
