# Generated by Django 3.1.6 on 2021-04-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_auto_20210406_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='copper',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='electrum',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='platinum',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='silver',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
