# Generated by Django 3.1.6 on 2021-05-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_weapon_weight'),
        ('character', '0010_money_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='adventuring_gear',
            field=models.ManyToManyField(blank=True, related_name='character', through='equipment.CharacterAdventuringGear', to='equipment.AdventuringGear'),
        ),
    ]
