# Generated by Django 3.1.6 on 2021-04-01 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0005_auto_20210401_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('prerequisite', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'feat',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CharacterFeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.JSONField(default=dict)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='features.feat')),
            ],
            options={
                'db_table': 'character_feat',
            },
        ),
        migrations.CreateModel(
            name='CharacterClassFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characterclass')),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='features.feat')),
            ],
            options={
                'db_table': 'character_class_feature',
            },
        ),
    ]
